@SocialMedia.Post.Command.Api_HostAddress = https://localhost:7258

GET {{SocialMedia.Post.Command.Api_HostAddress}}/weatherforecast/
Accept: application/json

###
###

POST {{SocialMedia.Post.Command.Api_HostAddress}}/posts/{postId}/like

###
